---
- name: Converge
  hosts: all
  roles:
    - role: waco_org.waco_python
  vars:
    - wapy_source_versions: []
    - wapy_has_ansible: true
    - wapy_has_mercurial: true
    - wapy_has_sphinx: true
