---
# Workstation as Code
# Copyright Nicola Musatti 2025.

- name: Install git (EL, Fedora)
  ansible.builtin.dnf:
    name:
      - git
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install git (Ubuntu)
  ansible.builtin.apt:
    name:
      - git
    state: present
  become: true
  when: ansible_os_family == 'Ubuntu'

- name: Checkout Waco Bootstrap
  ansible.builtin.git:
    repo: "https://github.com/waco-org/waco-bootstrap.git"
    dest: /tmp/waco-bootstrap

- name: Check if the waco user exists
  ansible.builtin.user:
    name: "waco"
  check_mode: true
  register: waco_user

- name: Run the waco-bootstrap script
  ansible.builtin.command: "/tmp/waco-bootstrap/waco-bootstrap"
  become: true
  when: waco_user.changed is defined and waco_user.changed

- name: Check if the waco/roles directory exists
  ansible.builtin.stat:
    path: /home/waco/waco/roles
  register: waco_roles

- name: Run the waco-provision script
  ansible.builtin.command: "/home/waco/waco/waco-provision"
  become: true
  when: waco_roles.stat.isdir is not defined or not waco_roles.stat.isdir
