---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: "Install Python {{ python_release }} from source"
  include_role:
    name: nmusatti.source_python

- name: "Install pip for Python {{ python_release }}"
  include_role:
    name: bobbyrenwick.pip
  vars:
    - python: "{{ source_python_root }}/Python-{{ python_minor }}/bin/python{{ python_minor }}"
    - pip: "{{ source_python_root }}/Python-{{ python_minor }}/bin/pip{{ python_minor }}"

- name: "Install standard packages on Python {{ python_release }}"
  pip:
    name: "{{ source_python_packages }}"
    executable: "{{ source_python_root }}/Python-{{ python_minor }}/bin/pip{{ python_minor }}"
    state: present
  become: true
  become_user: "{{ python_user }}"

- name: "Create base virtualenv directory for Python {{ python_release }}"
  file:
    dest: "{{ source_venv_root }}/{{ source_venv_prefix }}-{{ python_minor }}"
    state: directory
    mode: 0755
    group: "{{ python_group }}"
    owner: "{{ python_user }}"
  become: true

- name: "Install the default virtualenv for Python {{ python_release }}"
  pip:
    name: "{{ source_venv_packages }}"
    virtualenv: "{{ source_venv_root }}/{{ source_venv_prefix }}-{{ python_minor }}/{{ source_venv }}"
    virtualenv_command: "{{ source_python_root }}/Python-{{ python_minor }}/bin/virtualenv"
    virtualenv_python: "{{ source_python_root }}/Python-{{ python_minor }}/bin/python{{ python_minor }}"
  become: true
  become_user: "{{ python_user }}"

- name: "Register SELinux compatible release"
  set_fact:
    selinux_python_release: "{{ python_release }}"
  when: selinux_python_minor == python_minor

- name: "Register the most recent source release"
  set_fact:
    newest_python_release: "{{ python_release }}"
    newest_python_minor: "{{ python_release.split('.')[0] }}.{{ python_release.split('.')[1] }}"
  when: >
    newest_python_release is not defined or
    newest_python_release.split('.')[0] < python_release.split('.')[0] or (
    newest_python_release.split('.')[0] == python_release.split('.')[0] and
    newest_python_release.split('.')[1] < python_release.split('.')[1] )
