- name: "Register SELinux compatible source virtualenv tools"
  set_fact:
    selinux_virtualenv_dir: "{{ wapy_source_venv_root_dir }}/{{ wapy_source_venv_prefix }}-{{
    wapy_selinux_python_minor }}"
    selinux_virtualenv_command: "{{ wapy_install_root_dir }}/Python-{{
    wapy_selinux_python_minor }}/bin/virtualenv"
    selinux_virtualenv_python: "{{ wapy_install_root_dir }}/Python-{{
    wapy_selinux_python_minor }}/bin/python{{ wapy_selinux_python_minor }}"
  when: selinux_python_release is defined

- name: "Register SELinux compatible system virtualenv tools"
  set_fact:
    selinux_virtualenv_dir: "{{ wapy_system_venv_root_dir }}/{{ wapy_system_venv_prefix }}-{{
    wapy_selinux_python_minor }}"
    selinux_virtualenv_command: "/usr/bin/virtualenv{{
    ( wapy_platform == 'Fedora' ) | ternary ('', '-' + wapy_selinux_python_minor) }}"
    selinux_virtualenv_python: "/usr/bin/python{{ wapy_selinux_python_minor }}"
  when: selinux_python_release is not defined

- name: "Create root directory for system virtualenv's"
  file:
    dest: "{{ wapy_system_venv_root_dir }}"
    state: directory
    mode: 0755
  become: true
  when: ( wapy_has_ansible or wapy_has_mercurial or wapy_has_sphinx ) and selinux_python_release is not defined

- name: "Create base directory for system virtualenv's"
  file:
    dest: "{{ selinux_virtualenv_dir }}"
    state: directory
    mode: 0755
    group: "{{ wapy_group }}"
    owner: "{{ wapy_user }}"
  become: true
  when: ( wapy_has_ansible or wapy_has_mercurial or wapy_has_sphinx ) and selinux_python_release is not defined

- name: Install Ansible and Molecule in a virtualenv (EL 7)
  pip:
    name: "{{ wapy_ansible_packages }}"
    virtualenv: "{{ selinux_virtualenv_dir }}/{{ wapy_ansible_venv }}"
    virtualenv_command: "{{ selinux_virtualenv_command }}"
    virtualenv_python: "{{ selinux_virtualenv_python }}"
  environment:
    LC_ALL: "en_US.UTF-8"
  become: true
  become_user: "{{ wapy_user }}"
  when: wapy_has_ansible and wapy_platform == 'EL7'

- name: Install Ansible and Molecule in a virtualenv (EL 8, Fedora)
  pip:
    name: "{{ wapy_ansible_packages }}"
    virtualenv: "{{ selinux_virtualenv_dir }}/{{ wapy_ansible_venv }}"
    virtualenv_command: "{{ selinux_virtualenv_command }}"
    virtualenv_python: "{{ selinux_virtualenv_python }}"
  become: true
  become_user: "{{ wapy_user }}"
  when: wapy_has_ansible and wapy_platform != 'EL7'

- name: Install Mercurial in a virtualenv
  pip:
    name:
      - mercurial
      - selinux
    virtualenv: "{{ selinux_virtualenv_dir }}/hg"
    virtualenv_command: "{{ selinux_virtualenv_command }}"
    virtualenv_python: "{{ selinux_virtualenv_python }}"
  become: true
  become_user: "{{ wapy_user }}"
  when: wapy_has_mercurial
