---
- name: Converge
  hosts: all
  roles:
    - role: waco.waco_python
  vars:
    - wapy_source_versions:
        - 3.10.1
        - 3.9.9
        - 3.8.12
        - 3.7.12
        - 3.6.15
        - 2.7.18
    - wapy_has_ansible: true
    - wapy_has_mercurial: true
    - wapy_has_sphinx: true
